service: resumebook-backend
frameworkVersion: '4'

package:
  individually: true
  excludeDevDependencies: true

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  stage: ${opt:stage, 'prod'}
  environment:
    FIREBASE_PROJECT_ID: ${env:FIREBASE_PROJECT_ID}
    FIREBASE_PRIVATE_KEY: ${env:FIREBASE_PRIVATE_KEY}
    LINKEDIN_CLIENT_ID: ${env:LINKEDIN_CLIENT_ID}
    LINKEDIN_CLIENT_SECRET: ${env:LINKEDIN_CLIENT_SECRET}
    LINKEDIN_REDIRECT_URI: ${env:LINKEDIN_REDIRECT_URI}
    FRONTEND_REDIRECT_URI: ${env:FRONTEND_REDIRECT_URI}

# Disable v4's native esbuild so it doesn't try to stage .serverless/build/package.json
build:
  esbuild: false

functions:
  api:
    handler: handler.main
    package:
      patterns:
        - src/**
        - package.json
        - package-lock.json
        - node_modules/**         # include backend deps right from backend/
        # Optional: keep the zip lean
        - '!**/*.test.*'
        - '!**/__tests__/**'
        - '!**/.eslint*'
        - '!**/.prettier*'
        - '!**/*.md'
    events:
      - http:
          path: auth/linkedin
          method: get
          cors:
            origin: "*"
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false
      - http:
          path: auth/linkedin/callback
          method: get
          cors:
            origin: "*"
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false
      - http:
          path: student/create-invite
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false
      - http:
          path: student/redeem-invite
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false
      - http:
          path: admin/create-invite
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false
      - http:
          path: admin/redeem-invite
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false
