service: resumebook-backend
frameworkVersion: '4'

package:
  individually: true
  excludeDevDependencies: true

plugins: 
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  stage: ${opt:stage, 'prod'}
  environment: 
    FIREBASE_PROJECT_ID: ${env:FIREBASE_PROJECT_ID}
    FIREBASE_PRIVATE_KEY: ${env:FIREBASE_PRIVATE_KEY}
    LINKEDIN_CLIENT_ID: ${env:LINKEDIN_CLIENT_ID}
    LINKEDIN_CLIENT_SECRET: ${env:LINKEDIN_CLIENT_SECRET}

custom:
  esbuild:
    bundle: true        # bundle & tree-shake
    minify: false
    sourcemap: false
    target: 'node22'    
    external:
      - aws-sdk         # exclude AWS SDK (Lambda provides it)

functions:
  students:
    handler: src/functions/students/handler.main
    events:
      - http:
          path: students
          method: get
      - http:
          path: students
          method: post
      - http:
          path: students/{id}
          method: get
      - http:
          path: students/{id}
          method: put
      - http:
          path: students/{id}
          method: delete

  recruiters:
    handler: src/functions/recruiters/handler.main
    events:
      - http:
          path: recruiters/search
          method: post

  auth:
    handler: src/functions/auth/handler.main
    events:
      - http:
          path: auth/linkedin
          method: get
      - http:
          path: auth/linkedin/callback
          method: get
