functions:
  api:
    handler: src/handler.main
    package:
      patterns:
        - src/**
        - node_modules/**
    events:
      - http:
          path: auth/linkedin
          method: get
          cors: true
      - http:
          path: auth/linkedin/callback
          method: get
          cors: true
      - http:
          path: student/create-invite
          method: post
          cors: true
      - http:
          path: student/redeem-invite
          method: post
          cors: true
      - http:
          path: admin/create-invite
          method: post
          cors: true
      - http:
          path: admin/redeem-invite
          method: post
          cors: true
