service: resumebook-backend
frameworkVersion: '4'

package:
  individually: true
  excludeDevDependencies: true

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  stage: ${opt:stage, 'prod'}
  environment:
    FIREBASE_PROJECT_ID: ${env:FIREBASE_PROJECT_ID}
    FIREBASE_PRIVATE_KEY: ${env:FIREBASE_PRIVATE_KEY}
    LINKEDIN_CLIENT_ID: ${env:LINKEDIN_CLIENT_ID}
    LINKEDIN_CLIENT_SECRET: ${env:LINKEDIN_CLIENT_SECRET}

# Built-in esbuild in v4 (no serverless-esbuild plugin)
build:
  esbuild:
    bundle: true
    minify: false
    sourcemap: false
    external:
      - aws-sdk

functions:
  students:
    handler: src/functions/students
    events:
      - http:
          path: students
          method: get
      - http:
          path: students
          method: post
      - http:
          path: students/{id}
          method: get
      - http:
          path: students/{id}
          method: put
      - http:
          path: students/{id}
          method: delete

  recruiters:
    handler: src/functions/recruiters
    events:
      - http:
          path: recruiters/search
          method: post

  auth:
    handler: src/functions/auth
    events:
      - http:
          path: auth/linkedin
          method: get
      - http:
          path: auth/linkedin/callback
          method: get
