service: resumebook-backend
frameworkVersion: '4'

package:
  individually: true
  excludeDevDependencies: true

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  stage: ${opt:stage, 'prod'}
  environment:
    FIREBASE_PROJECT_ID: ${env:FIREBASE_PROJECT_ID}
    FIREBASE_PRIVATE_KEY: ${env:FIREBASE_PRIVATE_KEY}
    LINKEDIN_CLIENT_ID: ${env:LINKEDIN_CLIENT_ID}
    LINKEDIN_CLIENT_SECRET: ${env:LINKEDIN_CLIENT_SECRET}
    LINKEDIN_REDIRECT_URI: ${env:LINKEDIN_REDIRECT_URI}
    FRONTEND_REDIRECT_URI: ${env:FRONTEND_REDIRECT_URI}

# Built-in esbuild in v4 (no serverless-esbuild plugin)
build:
  esbuild:
    bundle: false
    minify: false
    sourcemap: true
    external:
      - aws-sdk
      - firebase-admin

functions:
  
  students:
    handler: src/functions/students/handler.hander
    events:
      - http:
          path: students
          method: get
      - http:
          path: students
          method: post
      - http:
          path: students/{id}
          method: get
      - http:
          path: students/{id}
          method: put
      - http:
          path: students/{id}
          method: delete

  recruiters:
    handler: src/functions/recruiters/handler.main
    events:
      - http:
          path: recruiters/search
          method: post

  auth:
    handler: src/functions/auth/handler.handler
    package:
      patterns:
        - src/functions/auth/**          # your code
        - src/shared/**
        - node_modules/axios/**          # <- include deps explicitly
        - node_modules/follow-redirects/**
        - node_modules/firebase-admin/**
        - node_modules/sonwebtoken/**
        - node_modules/jwks-rsa/**
    events:
      - http:
          path: auth/linkedin
          method: get
          cors: true
      - http:
          path: auth/linkedin/callback
          method: get