import { ProfileForm } from "@/app/hooks/useProfileForm";
import { SocialPlatform } from "@/components/filterComponents/LinkInput";

export const mockStudents: ProfileForm[] = [
  {
    firstName: "Sarah",
    lastName: "Chen",
    email: "sarah.chen@gmail.com",
    utdEmail: "sxc210045@utdallas.edu",
    phone: "469-555-0123",
    gpa: 3.85,
    gradYear: 2026,
    major: "Computer Science",
    gradSemester: "Spring",
    availability: ["Internship"],
    workAuthorized: true,
    profilePhoto: null,
    resumeUrl: "https://example.com/resumes/sarah-chen.pdf",
    links: {
      [SocialPlatform.Github]: "https://github.com/sarahchen",
      [SocialPlatform.LinkedIn]: "https://linkedin.com/in/sarahchen",
      [SocialPlatform.Twitter]: "",
      [SocialPlatform.Website]: "https://sarahchen.dev",
    },
  },
  {
    firstName: "Marcus",
    lastName: "Johnson",
    email: "mjohnson@protonmail.com",
    utdEmail: "mxj190067@utdallas.edu",
    phone: "214-555-7890",
    gpa: 3.42,
    gradYear: 2025,
    major: "Software Engineering",
    gradSemester: "Fall",
    availability: ["Full-time", "Internship"],
    workAuthorized: false,
    profilePhoto: null,
    resumeUrl: "https://example.com/resumes/marcus-johnson.pdf",
    links: {
      [SocialPlatform.Github]: "https://github.com/marcusj",
      [SocialPlatform.LinkedIn]: "https://linkedin.com/in/marcus-johnson-dev",
      [SocialPlatform.Twitter]: "https://twitter.com/marcuscodes",
      [SocialPlatform.Website]: "",
    },
  },
  {
    firstName: "Priya",
    lastName: "Patel",
    email: "priya.patel.utd@outlook.com",
    utdEmail: "pxp220156@utdallas.edu",
    phone: "972-555-4567",
    gpa: null,
    gradYear: 2027,
    major: "Data Science",
    gradSemester: null,
    availability: ["Internship"],
    workAuthorized: true,
    profilePhoto: null,
    resumeUrl: null,
    links: {
      [SocialPlatform.Github]: "",
      [SocialPlatform.LinkedIn]: "https://linkedin.com/in/priyapatel",
      [SocialPlatform.Twitter]: "",
      [SocialPlatform.Website]: "https://priyapatel.com",
    },
  },
];
