  # - name: Type Check Frontend
      #   run: |
      #     cd frontend && npm run type-check || echo "No type-check script"

      # - name: Prettier Format Check
      #   run: |
      #     npx prettier --check "frontend/**/*.{ts,tsx}" || echo "Formatting issues"
name: CI Checks

on:
  push:
    branches: main
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '.github/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Lint Frontend (if present)
        run: |
          if [ -f frontend/package.json ]; then
            cd frontend
            npm ci
            npm run lint || echo "No lint script or errors found"
          fi

      - name: Lint Backend (if present)
        run: |
          if [ -f backend/package.json ]; then
            cd backend
            npm ci
            npm run lint || echo "No lint script or errors found"
          fi
